# Generated by Django 3.2 on 2022-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('titleprivacypolicy', models.CharField(max_length=254, null=True)),
                ('bodyprivacypolicy', models.TextField(blank=True, default=True)),
                ('titletermsandconditions', models.CharField(max_length=254, null=True)),
                ('bodytermsandconditions', models.TextField(blank=True, default=True)),
                ('titlereturnspolicy', models.CharField(max_length=254, null=True)),
                ('bodyreturnspolicy', models.TextField(blank=True, default=True)),
            ],
        ),
    ]
