# Generated by Django 3.2 on 2022-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
