# Generated by Django 3.2 on 2022-03-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220304_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fork',
            new_name='feature1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='frame',
            new_name='feature2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='groupset',
            new_name='feature3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wheels',
            new_name='feature4',
        ),
    ]
